#' Get the installed `prepare_bam.sh` path
#'
#' Returns the absolute path to the bundled shell script distributed with
#' RiboBA under `inst/scripts/prepare_bam.sh`.
#'
#' @return A single absolute file path.
#' @keywords internal
prepare_bam_script_path <- function() {
  script <- system.file("scripts", "prepare_bam.sh", package = "RiboBA")
  if (script == "") {
    stop(
      "Cannot find bundled script 'prepare_bam.sh'. Please reinstall RiboBA.",
      call. = FALSE
    )
  }
  script
}

#' Prepare transcriptome-aligned BAM files
#'
#' Wrapper around the bundled `prepare_bam.sh` script.
#'
#' @param workdir Working directory for indices, logs, and generated BAM files.
#' @param fastq_dir Directory containing adapter-trimmed FASTQ files.
#' @param rrna_fa Path to rRNA FASTA used for depletion.
#' @param annotate_dir Optional directory generated by [build_annotation_index()].
#' @param genome_file Optional genome FASTA path, used by the script for species
#'   inference if `species` is missing.
#' @param species Optional species name.
#' @param cds_fa Optional CDS FASTA. If omitted, inferred from `annotate_dir`.
#' @param lncrna_fa Optional lncRNA FASTA. If omitted, inferred from
#'   `annotate_dir`.
#' @param threads Number of threads passed to the shell script.
#' @param config Optional YAML config file accepted by `prepare_bam.sh`.
#' @param script Optional path to the shell script. Defaults to bundled path.
#' @param stdout Passed to [base::system2()] `stdout`.
#' @param stderr Passed to [base::system2()] `stderr`.
#'
#' @return Invisibly returns process exit status (`0` means success).
#' @export
prepare_bam <- function(
    workdir,
    fastq_dir,
    rrna_fa,
    annotate_dir = NULL,
    genome_file = NULL,
    species = NULL,
    cds_fa = NULL,
    lncrna_fa = NULL,
    threads = 12,
    config = NULL,
    script = prepare_bam_script_path(),
    stdout = "",
    stderr = "") {
  validate_scalar_string <- function(x, name, required = FALSE) {
    if (is.null(x)) {
      if (required) {
        stop("`", name, "` is required.", call. = FALSE)
      }
      return(NULL)
    }
    if (!is.character(x) || length(x) != 1L || is.na(x) || !nzchar(x)) {
      stop("`", name, "` must be a non-empty character scalar.", call. = FALSE)
    }
    x
  }

  validate_optional_scalar <- function(x, name) {
    if (is.null(x)) {
      return(NULL)
    }
    if (length(x) != 1L || is.na(x)) {
      stop("`", name, "` must be a scalar when provided.", call. = FALSE)
    }
    x
  }

  workdir <- validate_scalar_string(workdir, "workdir", required = TRUE)
  fastq_dir <- validate_scalar_string(fastq_dir, "fastq_dir", required = TRUE)
  rrna_fa <- validate_scalar_string(rrna_fa, "rrna_fa", required = TRUE)
  annotate_dir <- validate_scalar_string(annotate_dir, "annotate_dir")
  genome_file <- validate_scalar_string(genome_file, "genome_file")
  species <- validate_scalar_string(species, "species")
  cds_fa <- validate_scalar_string(cds_fa, "cds_fa")
  lncrna_fa <- validate_scalar_string(lncrna_fa, "lncrna_fa")
  config <- validate_scalar_string(config, "config")
  script <- validate_scalar_string(script, "script", required = TRUE)
  if (!file.exists(script)) {
    stop("Script not found: ", script, call. = FALSE)
  }
  threads <- validate_optional_scalar(threads, "threads")

  args <- character(0)
  append_arg <- function(flag, value) {
    if (!is.null(value)) {
      args <<- c(args, flag, as.character(value))
    }
  }

  append_arg("--config", config)
  append_arg("--workdir", workdir)
  append_arg("--fastq-dir", fastq_dir)
  append_arg("--annotate-dir", annotate_dir)
  append_arg("--genome-file", genome_file)
  append_arg("--species", species)
  append_arg("--rrna-fa", rrna_fa)
  append_arg("--cds-fa", cds_fa)
  append_arg("--lncrna-fa", lncrna_fa)
  append_arg("--threads", as.character(threads))

  status <- system2(
    command = "bash",
    args = c(script, args),
    stdout = stdout,
    stderr = stderr
  )

  if (!identical(status, 0L)) {
    stop("prepare_bam.sh failed with exit status ", status, call. = FALSE)
  }

  invisible(status)
}
